TrajectoryPlannerROS:
    max_vel_x:  0.1
    min_vel_x: 0.01

    max_vel_theta: 0.26
    min_vel_theta: -0.26

    min_in_place_vel_theta: 0.3

    acc_lim_th: 0.5
    acc_lim_x: 1.1
    acc_lim_y: 1.1

    yaw_goal_tolerance: 0.2 #0.05
    xy_goal_tolerance: 0.1

    latch_xy_goal_tolerance: false

    sim_time: 2
    holonomic_robot: false

    escape_velocity: -0.1

    controller_frequency: 2
