obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.8, 0.8], [-0.8, 0.8], [-0.8, -0.8], [0.8, -0.8] ]
robot_radius: 0.16
inflation_radius: 0.1

tranform_tolerance: 1.5
observation_sources: laser_scan_sensor 


controller_frequency: 2.0
laser_scan_sensor: {sensor_frame: camera_depth_frame, data_typa: LaserScan, topic: /scan, marking: true, clearing: true}
